name = "SlaterKoster"
uuid = "791802c2-cbbe-11e8-11fc-77a5a8b1b40e"
authors = ["Sakse Dalum <dalum@users.noreply.github.com>"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
